#!/usr/bin/env python3
"""Generate the ten-unit curriculum menu from docs/unit-*.md files.

The generated module is used by the SPA routes, the learning sidebar, and the
learning sidebar. Run this after changing docs; Dockerfile runs it too so a
push always deploys the exact document set bundled in the image.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
INDEX_HTML = ROOT / "app" / "frontend" / "index.html"
OUT_MODULE = ROOT / "app" / "frontend" / "js" / "data" / "learnDocs.js"
CURRICULUM_DOCS = (
    ("unit-01", "1. 금융시장과 금융상품"),
    ("unit-02", "2. 주식·ETF와 시장"),
    ("unit-03", "3. 채권·금리·신용위험"),
    ("unit-04", "4. 파생상품과 헤지"),
    ("unit-05", "5. 재무제표와 현금흐름"),
    ("unit-06", "6. 기업가치평가"),
    ("unit-07", "7. 거시경제와 시장지표"),
    ("unit-08", "8. 산업·기업·기술적 분석"),
    ("unit-09", "9. 포트폴리오와 자산배분"),
    ("unit-10", "10. 리스크·백테스트·RAG"),
)


def title_for(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return re.sub(r"^(?:Day|DAY)\s+\d+\s*[—-]\s*", "", match.group(1)).strip()
    return path.stem


def menu_html(docs: list[dict[str, str]]) -> str:
    rows = []
    for doc in docs:
        icon = "fa-spell-check" if doc["id"] == "voca" else "fa-circle-dot"
        rows.append(
            f'            <a class="nav-item" data-view="learn-{html.escape(doc["id"])}">'
            f'<i class="fa-solid {icon}"></i>{html.escape(doc["label"])}</a>'
        )
    return "\n".join(rows)


def main() -> None:
    def load_docs(entries: tuple[tuple[str, str], ...]) -> list[dict[str, str]]:
        docs = []
        for doc_id, label in entries:
            path = DOCS_DIR / f"{doc_id}.md"
            title = title_for(path)
            docs.append({"id": doc_id, "file": path.name, "title": title, "label": label})
        return docs

    docs = load_docs(CURRICULUM_DOCS)

    OUT_MODULE.write_text(
        "// Generated by scripts/sync_learning_menu.py from docs/*.md. Do not edit manually.\n"
        f"export const LEARN_DOCS = {json.dumps(docs, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )

    source = INDEX_HTML.read_text(encoding="utf-8")
    replacements = {"curriculum": menu_html(docs)}
    for section_id, rows in replacements.items():
        replacement = f'<div class="nav-children" id="nav-{section_id}">\n{rows}\n          </div>'
        source, count = re.subn(
            rf'<div class="nav-children(?: open)?" id="nav-{section_id}">.*?</div>',
            replacement,
            source,
            count=1,
            flags=re.S,
        )
        if count != 1:
            raise SystemExit(f"index.html에서 {section_id} 학습 메뉴를 찾지 못했습니다.")

    INDEX_HTML.write_text(source, encoding="utf-8")
    print(f"통합 금융 커리큘럼 메뉴 동기화 완료: {len(docs)}개 단원")


if __name__ == "__main__":
    main()
